# Generated by Django 6.0.5 on 2026-05-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formanswer',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='formanswer',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formquestion',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Textarea'), ('radio', 'Radio Button'), ('checkbox', 'Checkbox'), ('select', 'Dropdown'), ('rating', 'Rating'), ('number', 'Number'), ('email', 'Email'), ('date', 'Date'), ('file', 'Resume Upload')], default='text', max_length=50),
        ),
    ]
