# Generated by Django 6.0.5 on 2026-05-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0002_formanswer_uploaded_file_alter_formanswer_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formquestion',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Textarea'), ('radio', 'Radio Button'), ('checkbox', 'Checkbox'), ('select', 'Dropdown'), ('rating', 'Rating'), ('number', 'Number'), ('email', 'Email'), ('date', 'Date')], default='text', max_length=50),
        ),
    ]
