# Generated by Django 6.0.5 on 2026-05-21 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0003_alter_formquestion_field_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicformresponse',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='publicformresponse',
            name='college',
        ),
        migrations.RemoveField(
            model_name='publicformresponse',
            name='email',
        ),
        migrations.RemoveField(
            model_name='publicformresponse',
            name='name',
        ),
    ]
