# Generated by Django 4.2.30 on 2026-07-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0004_remove_publicformresponse_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicform',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='formanswer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='formquestion',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Textarea'), ('number', 'Number'), ('float', 'Decimal Number'), ('email', 'Email'), ('phone', 'Phone Number'), ('pan', 'PAN Number'), ('apaar_id', 'APAAR ID'), ('date', 'Date'), ('radio', 'Radio Button'), ('checkbox', 'Checkbox'), ('select', 'Dropdown'), ('rating', 'Rating')], default='text', max_length=50),
        ),
        migrations.AlterField(
            model_name='formquestion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publicformanswer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publicformresponse',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
