# Generated by Django 4.2.30 on 2026-07-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0005_alter_dynamicform_id_alter_formanswer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formquestion',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Textarea'), ('number', 'Number'), ('float', 'Decimal Number'), ('email', 'Email'), ('phone', 'Phone Number'), ('pan', 'PAN Number'), ('apaar_id', 'APAAR ID'), ('aadhaar', 'Aadhaar Number'), ('date', 'Date'), ('radio', 'Radio Button'), ('checkbox', 'Checkbox'), ('select', 'Dropdown'), ('rating', 'Rating')], default='text', max_length=50),
        ),
    ]
