# Generated by Django 4.2.30 on 2026-07-29 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0006_alter_formquestion_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicform',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='form_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_update', 'Pending Update'), ('locked', 'Locked')], default='submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='publicformresponse',
            name='form_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='publicformresponse',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_update', 'Pending Update'), ('locked', 'Locked')], default='submitted', max_length=20),
        ),
        migrations.CreateModel(
            name='FormQuestionCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Not Equals'), ('contains', 'Contains'), ('greater_than', 'Greater Than'), ('less_than', 'Less Than')], default='equals', max_length=20)),
                ('trigger_value', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('show', 'Show'), ('hide', 'Hide'), ('require', 'Require')], default='show', max_length=20)),
                ('condition_type', models.CharField(default='AND', max_length=10)),
                ('parent_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_conditions', to='forms_engine.formquestion')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='forms_engine.formquestion')),
            ],
        ),
    ]
