# Generated by Django 4.2.30 on 2026-07-30 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0007_dynamicform_version_formresponse_form_version_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formquestion',
            options={'ordering': ['order', 'id']},
        ),
    ]
